import "./src/env.ts"; // validate env at build time
import withPWAInit from "@ducanh2912/next-pwa";

const withPWA = withPWAInit({
  dest: "public",
  disable: process.env.NODE_ENV === "development",
  register: true,
});

// SEC-06: 'unsafe-eval' is required by Next.js HMR in development but must be
// removed in production builds where it would permit XSS payload execution.
// 'unsafe-inline' remains for now; migrate to a nonce-based CSP via
// src/middleware.ts to eliminate it in a future hardening pass.
const isDev = process.env.NODE_ENV === "development";
const scriptSrc = isDev
  ? "script-src 'self' 'unsafe-eval' 'unsafe-inline'"
  : "script-src 'self' 'unsafe-inline'";

// QR-SEC-01: 'worker-src self' allows the PWA service worker (generated by
// @ducanh2912/next-pwa at build time) to be registered. Without this directive,
// Chrome and Firefox fall back to child-src which may block SW registration in
// future browser versions as worker-src gains wider support.
//
// QR-SEC-01: 'manifest-src self' explicitly permits the browser to fetch
// /manifest.json. Without this, some strict CSP configurations (especially
// on Firefox) block manifest loading and prevent PWA installation prompts.
//
// Neither directive introduces new attack surface — both are restricted to 'self'.
const workerSrc = "worker-src 'self'";
const manifestSrc = "manifest-src 'self'";

const securityHeaders = [
  { key: "X-DNS-Prefetch-Control", value: "on" },
  { key: "X-Frame-Options", value: "SAMEORIGIN" },
  { key: "X-Content-Type-Options", value: "nosniff" },
  { key: "Referrer-Policy", value: "strict-origin-when-cross-origin" },
  {
    key: "Permissions-Policy",
    // camera=(self): required by html5-qrcode on the merchant scanner page.
    // microphone=() and geolocation=(): explicitly denied — Suiki never needs these.
    value: "camera=(self), microphone=(), geolocation=()",
  },
  {
    key: "Content-Security-Policy",
    value: [
      "default-src 'self'",
      scriptSrc,
      "style-src 'self' 'unsafe-inline'",
      // img-src: data: covers QR canvas toDataURL(); blob: covers
      // beautiful-qr-code SVG-to-blob download links and camera preview frames.
      // SEC-07: img-src * allows any merchant image domain (loyalty card artwork,
      // merchant logos stored on IPFS or arbitrary CDNs). This is intentional for
      // the MVP but should be tightened to a known CDN allowlist before mainnet.
      "img-src * data: blob:",
      "font-src 'self'",
      // media-src: blob: is required for html5-qrcode to attach camera
      // MediaStream output to a <video> element via createObjectURL().
      "media-src 'self' blob:",
      workerSrc,
      manifestSrc,
      isDev
        ? "connect-src 'self' https://fullnode.testnet.sui.io https://fullnode.mainnet.sui.io https://fullnode.devnet.sui.io wss://fullnode.testnet.sui.io https://*.trycloudflare.com wss://*.trycloudflare.com"
        : "connect-src 'self' https://fullnode.testnet.sui.io https://fullnode.mainnet.sui.io https://fullnode.devnet.sui.io wss://fullnode.testnet.sui.io",
    ].join("; "),
  },
];

export default withPWA({
  reactStrictMode: true,
  experimental: {
    viewTransition: true,
  },
  // Allow cloudflared quick tunnels (*.trycloudflare.com) to receive HMR
  // WebSocket connections in dev. Next.js 15+ rejects non-localhost origins
  // with "Unauthorized" by default.
  ...(isDev && {
    allowedDevOrigins: ["*.trycloudflare.com"],
  }),
  // Explicitly declare Turbopack config so Next.js 16 doesn't error on the
  // webpack config that @ducanh2912/next-pwa injects (PWA SW is built at
  // production build time, not during Turbopack dev server).
  turbopack: {},
  headers: async () => [
    {
      source: "/(.*)",
      headers: securityHeaders,
    },
  ],
});
